<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-S9EBEV5B" failures="1" tests="11" name="com.Runner.Amazon" time="260.550" errors="0" timestamp="2024-05-28T13:02:06 IST" skipped="0">
  <testcase classname="com.Runner.Amazon" name="inValidEmailId" time="24.297"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="validEmailIdAndInvalidPassword" time="21.530"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="emailIdWithEmptyText" time="4.532"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="validEmailIdWithEmptyPassword" time="6.410"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="validLoginTest" time="11.868">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.Runner.Amazon.validLoginTest(Amazon.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="searchProduct" time="61.140"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="searchProduct2" time="82.064"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="searchProduct3" time="19.700"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="searchProductWithInvalidName" time="2.981"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="makePayment" time="22.078"/>
  <system-out/>
  <testcase classname="com.Runner.Amazon" name="amazonSignOut" time="3.950"/>
  <system-out/>
</testsuite> <!-- com.Runner.Amazon -->
